name: CNIP Auto Update

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. 依赖
      - run: pip install requests netaddr

      # 4. 生成 CNIP
      - run: python src/build.py

      # 5. Git提交
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          
          # 只要内容有变（时间戳变了），就会提交成功
          # 如果没变（基本不可能，因为有时间戳），则跳过 commit 避免报错
          git diff --staged --quiet || git commit -m "CNIP update $(date -d '8 hours' '+%Y-%m-%d %H:%M:%S')"
          
          git push origin main
