name: update-cn-ip

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python src/build.py

      - name: commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/cn_ip.txt
          git commit -m "auto update cn ip" || echo "no changes"
          git push
